In [1]:
import requests
from bs4 import BeautifulSoup
import json
import os
import openpyxl
import time
import pandas as pd
from IPython.display import clear_output

In [ ]:
os.getcwd()

In [ ]:
# # from openpyxl import load_workbook
# import openpyxl
wb = openpyxl.load_workbook(filename = 'data.xlsx')
ws = wb["data"]
rawdata = []
for i in range(1, 3):
    row = []
    for j in range(1, 6):
        row.append(ws.cell(row=i, column=j).value)
    rawdata.append(row)
pd.DataFrame(rawdata)
#         print(ws.cell(row=i, column=j).value)

In [ ]:
temp = []
row = []
for i in range(1, 11):
    row.append(i)
    if(i%5==0):
        temp.append(row)
        row = []
pd.DataFrame(temp)

In [ ]:
for i in range(0, len(temp)):
    rawdata.append(temp[i])

In [ ]:
for i in range(0, len(rawdata)):
    for j in range(0, 5):
        ws.cell(row=i+1, column=j+1).value = rawdata[i][j]
wb.save(filename = 'data.xlsx')

In [7]:
pd.DataFrame(report)

,0,1,2,3,4,5,6,7,8
0,107/01/02,"13,698,944","499,370,945",36.45,36.60,36.05,36.55,+0.10,"3,932"
1,107/01/03,"19,959,825","737,353,608",36.50,37.35,36.25,37.35,+0.80,"5,001"
2,107/01/04,"14,927,721","555,392,977",37.35,37.45,36.75,37.20,-0.15,"5,698"
3,107/01/05,"35,536,815","1,325,926,954",37.50,37.50,37.05,37.30,+0.10,"7,554"
4,107/01/08,"22,660,681","858,574,153",37.40,38.30,37.20,38.20,+0.90,"7,513"
5,107/01/09,"19,053,008","728,607,834",38.10,38.55,37.90,38.30,+0.10,"6,170"
6,107/01/10,"11,674,625","447,720,584",38.30,38.50,38.00,38.45,+0.15,"4,366"
7,107/01/11,"35,062,055","1,322,632,044",38.30,38.35,37.45,37.50,-0.95,"10,505"
8,107/01/12,"18,804,747","707,643,024",37.75,37.95,37.35,37.60,+0.10,"7,168"
9,107/01/15,"9,637,157","363,246,276",37.65,37.85,37.55,37.85,+0.25,"2,849"
10,107/01/16,"9,338,163","354,474,155",37.95,38.10,37.70,38.10,+0.25,"3,315"
11,107/01/17,"12,716,828","487,501,985",38.00,38.50,37.90,38.50,+0.40,"4,645"
12,107/01/18,"13,010,910","497,368,272",38.60,38.65,37.75,37.85,-0.65,"3,842"
13,107/01/19,"8,346,117","316,437,594",37.95,38.10,37.75,37.90,+0.05,"2,707"
14,107/01/22,"8,771,524","330,896,083",37.90,37.90,37.55,37.85,-0.05,"2,258"
15,107/01/23,"13,647,470","507,908,931",37.80,37.80,36.85,37.30,-0.55,"4,030"
16,107/01/24,"8,517,283","316,930,360",37.45,37.45,36.90,37.30,0.00,"3,140"
17,107/01/25,"6,043,087","226,919,435",37.30,37.65,37.25,37.60,+0.30,"2,619"
18,107/01/26,"10,584,133","401,558,643",37.75,38.20,37.50,38.20,+0.60,"3,584"
19,107/01/29,"5,861,953","222,753,951",38.30,38.40,37.70,37.95,-0.25,"2,264"
20,107/01/30,"5,942,325","224,959,885",38.00,38.05,37.70,37.90,-0.05,"2,442"
21,107/01/31,"5,410,009","203,905,328",37.60,37.90,37.35,37.65,-0.25,"1,594"
22,107/02/01,"3,056,615","115,669,003",37.65,37.95,37.65,37.90,+0.25,"1,646"
23,107/02/02,"5,492,531","207,486,099",38.00,38.00,37.40,37.90,0.00,"1,625"
24,107/02/05,"6,630,801","248,021,263",37.10,37.80,37.10,37.80,-0.10,"2,573"
25,107/02/06,"25,755,973","918,764,863",36.80,36.80,34.80,35.50,-2.30,"7,529"
26,107/02/07,"12,732,168","463,756,335",36.10,36.80,36.00,36.40,+0.90,"4,546"
27,107/02/08,"7,998,055","293,917,031",36.55,36.85,36.50,36.75,+0.35,"2,424"
28,107/02/09,"13,739,138","488,833,188",35.30,36.20,35.10,35.60,-1.15,"5,837"
29,107/02/12,"6,017,173","215,201,803",35.60,36.20,35.30,35.95,+0.35,"2,135"
...,...,...,...,...,...,...,...,...,...
47,107/03/19,"1,979,911","74,117,085",37.45,37.55,37.20,37.55,-0.05,"1,122"
48,107/03/20,"4,111,790","152,892,358",37.35,37.35,36.95,37.35,-0.20,"1,869"
49,107/03/21,"3,697,305","137,932,173",37.45,37.45,37.15,37.35,0.00,"1,340"
50,107/03/22,"5,532,247","207,487,077",37.35,37.65,37.30,37.55,+0.20,"2,428"
51,107/03/23,"7,492,897","276,252,089",36.80,37.00,36.65,37.00,-0.55,"3,518"
52,107/03/26,"4,166,613","152,510,668",36.85,36.90,36.35,36.60,-0.40,"1,699"
53,107/03/27,"4,487,686","166,089,382",36.80,37.20,36.80,37.15,+0.55,"2,089"
54,107/03/28,"2,851,838","105,431,406",37.10,37.10,36.80,37.00,-0.15,"1,499"
55,107/03/29,"5,977,425","218,628,760",36.65,36.80,36.35,36.55,-0.45,"2,984"
56,107/03/30,"5,089,666","186,072,529",36.50,36.80,36.40,36.60,+0.05,"2,590"
57,107/03/31,"2,174,618","79,636,264",36.60,36.70,36.55,36.55,-0.05,"1,642"
58,107/04/02,"2,845,216","104,324,632",36.55,36.85,36.50,36.65,+0.10,"2,109"
59,107/04/03,"5,855,277","214,333,753",36.30,36.95,36.20,36.95,+0.30,"2,567"
60,107/04/09,"7,648,516","285,007,547",37.40,37.45,37.15,37.35,+0.40,"2,870"
61,107/04/10,"15,951,693","604,662,034",37.25,38.40,37.25,38.20,+0.85,"6,656"
62,107/04/11,"9,408,389","361,132,372",38.45,38.80,38.15,38.45,+0.25,"5,317"
63,107/04/12,"5,506,470","210,110,310",38.60,38.60,37.90,38.10,-0.35,"3,253"
64,107/04/13,"4,607,344","175,864,974",38.00,38.40,37.90,38.20,+0.10,"2,125"
65,107/04/16,"3,419,974","130,154,801",38.00,38.25,37.90,38.25,+0.05,"2,141"
66,107/04/17,"7,776,022","294,965,319",38.25,38.25,37.60,38.00,-0.25,"3,297"
67,107/04/18,"4,558,474","173,762,726",38.00,38.35,38.00,38.20,+0.20,"2,060"
68,107/04/19,"14,831,475","575,151,141",38.10,39.20,38.00,39.00,+0.80,"6,361"
69,107/04/20,"12,463,820","486,178,653",38.90,39.30,38.60,38.75,-0.25,"4,834"
70,107/04/23,"4,833,651","188,012,218",38.75,39.10,38.70,38.90,+0.15,"2,431"
71,107/04/24,"37,557,211","1,522,904,651",39.50,41.00,39.50,40.85,+1.95,"13,090"
72,107/04/25,"15,615,426","629,724,668",40.65,40.90,39.85,40.20,-0.65,"5,537"
73,107/04/26,"14,998,877","608,909,480",40.25,40.90,40.25,40.50,+0.30,"5,027"
74,107/04/27,"11,059,291","447,114,898",40.90,40.90,40.10,40.30,-0.20,"4,273"
75,107/04/30,"13,728,774","556,321,565",40.70,40.85,40.15,40.85,+0.55,"7,609"
76,107/05/02,"15,413,381","632,421,831",40.85,41.40,40.70,40.85,0.00,"5,448"